"""
build_readme_qa.py -- regenerates the "Questions Nakshatra Can Answer" section
of README.md from knowledge_base/heritage.json, so the documentation can never
drift from what the device actually says.

    python scripts/build_readme_qa.py           # rewrite the section in place
    python scripts/build_readme_qa.py --check   # exit 1 if README.md is stale
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KB_PATH = ROOT / "knowledge_base" / "heritage.json"
README = ROOT / "README.md"
BEGIN, END = "<!-- QA:BEGIN (generated by scripts/build_readme_qa.py -- do not edit by hand) -->", "<!-- QA:END -->"


def render() -> str:
    kb = json.loads(KB_PATH.read_text(encoding="utf-8"))
    topics = kb["topics"]
    n_q = sum(1 + len(t["alternative_questions"]) for t in topics)
    out = [BEGIN, "",
           f"**{len(topics)} topics · {n_q} listed phrasings · {len(kb['categories'])} categories.** "
           "Each topic has one spoken answer. The first question under a topic is the primary phrasing; "
           "the others are listed alternatives. Because matching is by name, description and sound, many "
           "unlisted wordings work too (\"Give me information about Konark\", \"the festival of lights\").", ""]
    n = 0
    for cat in kb["categories"]:
        members = [t for t in topics if t["category"] == cat["id"]]
        out += [f"### {cat['name']} ({len(members)})", ""]
        for t in members:
            n += 1
            out.append(f"**{n}. {t['name']}** &nbsp;`{t['id']}`")
            out.append("")
            for q in [t["question"], *t["alternative_questions"]]:
                out.append(f"- “{q}”")
            if t.get("descriptors"):
                out.append(f"- *also understood when described as:* {', '.join(t['descriptors'])}")
            out += ["", f"> {t['answer']}", ""]
    out.append(END)
    return "\n".join(out)


def main() -> int:
    text = README.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print("README.md has no QA markers", file=sys.stderr)
        return 1
    head, rest = text.split(BEGIN, 1)
    tail = rest.split(END, 1)[1]
    new = head + render() + tail
    if "--check" in sys.argv:
        if new != text:
            print("README.md is out of date -- run: python scripts/build_readme_qa.py")
            return 1
        print("README question list matches the knowledge base")
        return 0
    README.write_text(new, encoding="utf-8")
    print("README.md updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
