/**
 * export_android_motifs.mjs -- regenerates the Android app's line art from the
 * website's frontend/js/art.js, so both clients draw the same 22 motifs.
 *
 *   node scripts/export_android_motifs.mjs
 *
 * Every SVG element art.js emits (circle, line, ellipse, path) is rewritten as
 * path data and written to
 * android/app/src/main/java/com/nakshatra/heritage/ui/art/MotifData.kt.
 */

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "android/app/src/main/java/com/nakshatra/heritage/ui/art/MotifData.kt");
const { motifSVG, PALETTE } = await import(pathToFileURL(resolve(ROOT, "frontend/js/art.js")));

// Same order as the MOTIFS table in art.js.
const NAMES = ["wheel", "dome", "gopuram", "chaitya", "shikhara", "stupa", "stepwell", "vihara", "fort", "minar", "lamp",
  "dancer", "veena", "fish", "pot", "loom", "thali", "lotus", "mandala", "ghat", "mask", "sundial"];

const n = (v) => Number(Number(v).toFixed(2));
const oval = (cx, cy, rx, ry) => `M${n(cx - rx)} ${n(cy)}a${rx} ${ry} 0 1 0 ${n(rx * 2)} 0a${rx} ${ry} 0 1 0 ${n(-rx * 2)} 0Z`;

function shapes(name) {
  const svg = motifSVG(name);
  const inner = svg.slice(svg.indexOf(">") + 1, svg.lastIndexOf("</svg>"));
  const out = [];
  for (const [, tag, raw] of inner.matchAll(/<(circle|line|path|ellipse)\s+([^>]*?)\/?>/g)) {
    const a = Object.fromEntries([...raw.matchAll(/([\w-]+)="([^"]*)"/g)].map((m) => [m[1], m[2]]));
    let d;
    if (tag === "circle") d = oval(+a.cx, +a.cy, +a.r, +a.r);
    else if (tag === "ellipse") d = oval(+a.cx, +a.cy, +a.rx, +a.ry);
    else if (tag === "line") d = `M${a.x1} ${a.y1}L${a.x2} ${a.y2}`;
    else d = a.d;
    const shape = { d };
    if (a["stroke-width"]) shape.w = +a["stroke-width"];
    if (a.fill === "currentColor") shape.style = a.stroke === "none" ? "FILL" : "BOTH";
    if (a["stroke-dasharray"]) shape.dash = a["stroke-dasharray"].split(/[\s,]+/).map(Number);
    if (a.transform) {
      const t = a.transform.match(/translate\(([-\d.]+)[ ,]+([-\d.]+)\)\s*rotate\(([-\d.]+)\)/);
      if (!t) throw new Error(`unsupported transform in ${name}: ${a.transform}`);
      [shape.tx, shape.ty, shape.rot] = [+t[1], +t[2], +t[3]];
    }
    out.push(shape);
  }
  if (!out.length) throw new Error(`motif ${name} produced no shapes`);
  return out;
}

const kt = (s) => {
  const args = [JSON.stringify(s.d)];
  if (s.w != null) args.push(`w = ${s.w}f`);
  if (s.style) args.push(`style = ShapeStyle.${s.style}`);
  if (s.dash) args.push(`dash = floatArrayOf(${s.dash.map((v) => `${v}f`).join(", ")})`);
  if (s.tx != null) args.push(`tx = ${s.tx}f`, `ty = ${s.ty}f`, `rot = ${s.rot}f`);
  return `        S(${args.join(", ")}),`;
};

const lines = [
  "// GENERATED by scripts/export_android_motifs.mjs from frontend/js/art.js -- do not edit by hand.",
  "package com.nakshatra.heritage.ui.art",
  "",
  "internal enum class ShapeStyle { STROKE, FILL, BOTH }",
  "",
  "/** One path of a motif, in the 200 x 200 box art.js draws in. `w` = 0 means \"the motif's base stroke width\". */",
  "internal class S(",
  "    val d: String,",
  "    val w: Float = 0f,",
  "    val style: ShapeStyle = ShapeStyle.STROKE,",
  "    val dash: FloatArray? = null,",
  "    val tx: Float = 0f,",
  "    val ty: Float = 0f,",
  "    val rot: Float = 0f,",
  ")",
  "",
  "internal val MOTIF_DATA: Map<String, List<S>> = mapOf(",
];
for (const name of NAMES) {
  lines.push(`    ${JSON.stringify(name)} to listOf(`, ...shapes(name).map(kt), "    ),");
}
lines.push(")", "", "/** Category id -> the two gradient stops used on the website (PALETTE in art.js). */",
  "internal val CATEGORY_PALETTE: Map<String, Pair<Long, Long>> = mapOf(");
for (const [id, [a, b]] of Object.entries(PALETTE)) {
  lines.push(`    ${JSON.stringify(id)} to (0xFF${a.slice(1).toUpperCase()} to 0xFF${b.slice(1).toUpperCase()}),`);
}
lines.push(")", "");

writeFileSync(OUT, lines.join("\n").replace(/\$/g, "\\$"));
console.log(`wrote ${OUT}: ${NAMES.length} motifs`);
